name: Publish image to Github Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build --file .\docker\app_server\Dockerfile -t ghcr.io/psubiantogmail/lmm-ghcr:latest .
      - name: publish
        run: |
          docker push ghcr.io/psubiantogmail/lmm-ghcr:latest